services:
  # 1. Your Database
  mysql:
    image: mysql:8.0
    container_name: typingrace-mysql
    environment:
      MYSQL_DATABASE: typing_race_db
      MYSQL_ROOT_PASSWORD: nav1234
    ports:
      - "3306:3306"
    # --- ADD THIS HEALTHCHECK ---
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  # 2. Redis Cache
  redis:
    image: redis:7-alpine
    container_name: typingrace-redis
    ports:
      - "6379:6379"

  # 3. Apache Kafka
  kafka:
    image: apache/kafka:3.7.0
    container_name: typingrace-kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: 'Jg0Q5xZ1Q-mU9Q_V1M0w1A'

  # 4. Your Spring Boot App
  backend:
    build: .
    container_name: typingrace-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/typing_race_db?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=nav1234
      # FORCE Spring to use the Docker service names instead of localhost
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - LOGGING_LEVEL_ORG_APACHE_KAFKA=WARN
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_KAFKA=WARN
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
      kafka:
        condition: service_started